title: "state lock conflict"
level: intermediate
tools: [terraform, minIo, consul]
description: "State lock → multiple people can't edit infra at the same time"
category: "terraform"
created_on: 2025-08-04
